[package]
name = "avr-avogadro"
version = "0.1.0"
authors = ["Matías Lafroce <mlafroce@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2.62"

[build-dependencies]
cmake = "0.1"
